### ISSUE TITLE
UITableViewCellStyleSubtitle

### ISSUE THREAD

**Issue by magnett** [John-Lluch/SWRevealTableViewCell#1]
Hi!
I have a UITableViewCell using UITableViewCellStyleSubtitle from IB.
After using SWRevealTableViewCell the subtitle isn;t visible anymore.
Any suggestions?

**Comment by John-Lluch** [comment]
Hi, not sure what could cause this. I will try to reproduce this later. Have you tried to set background colors or text color to your subtitle label so you can figure out what could be going on. Thanks.

**Comment by magnett** [comment]
I tried to set textcolor with no success

**Comment by John-Lluch** [comment]
Hi, It works for me. I just pushed version 0.2.1 with some minor bug fixes and code refactoring. The example now creates cells with the subtitle style. They work just fine on the example. Maybe there's something on your code. If you find it please post it here so I can fix it in case it is related with the class. Thanks.

**Comment by John-Lluch** [comment]
I consider this issue fixed
