### ISSUE TITLE
How to properly reset all button items?

### ISSUE THREAD

**Issue by stevemckenzie** [John-Lluch/SWRevealTableViewCell#10]
I'm trying to change items when a user logs in or logs out and I'm noticing it keep the old items there but also add the new ones.

What public API can I use to do this? I see some private methods for this.

**Comment by John-Lluch** [comment]
I replied as well to your related post #6. However I do not understand what you mean by "how to reset all button items". The class will pick an array of items from the delegate every time you start panning the cell (left or right), that array should contain the actual items you want to present, so there's no need for any reseting of "old" items. So what is the actual issue?. Thanks.

**Comment by stevemckenzie** [comment]
@John-Lluch as per my response in #6 , what I am noticing is the old button items are still in the view hierarchy and not actually removed when you change button items on a visible cell. Basically the new items will end up being placed over top of the previous items.

This must be related to #6 and some type of bug around changing button items. This started out as a question / support, but after more review, has to be an edge case bug.

Basically I have "posts" shown in a tableview. If the user is logged in, and they own some of these posts, the reveal cell will provide an edit button.

If you logout, and i toggle a reloadData on the table to refresh the cells and also hide the button items, that edit button is still there but not entirely visible.

![screen shot 2014-07-29 at 11 36 49 am](https://cloud.githubusercontent.com/assets/32743/3739896/73d8cfc4-174f-11e4-93d2-d771d497759c.png)

![ios simulator screen shot jul 29 2014 11 37 22 am](https://cloud.githubusercontent.com/assets/32743/3739900/89a431b8-174f-11e4-89dc-1f7f4fd98580.png)

As you can see in the second screenshot, there's like 1px line. That is actually the edit button from the first screenshot.

**Comment by John-Lluch** [comment]
I can't reproduce this issue on my own code but I am willing to fix this for you. Please can you reply to #6, as I understand that both issues are related? Thanks

**Comment by John-Lluch** [comment]
Hi, @stevemckenzie.

Please can you test the latest version v0.3.4 that I submitted just several minutes ago?

Thanks.

**Comment by stevemckenzie** [comment]
:+1: thanks @John-Lluch !
