### ISSUE TITLE
iOS 8 animation is not consistent.

### ISSUE THREAD

**Issue by stevemckenzie** [John-Lluch/SWRevealTableViewCell#11]
I expect some issues around this with what they have added to iOS.

What I notice is sometimes when you swipe, the content view completely bounces over to the other side before coming back causing a jumping effect.

Other than that detail, it works great on both iOS 7 and 8.

**Comment by John-Lluch** [comment]
Hi @stevemckenzie. What do you exactly mean by "completely bounces over to the other side before coming back causing a jumping effect"? Isn't this a desired behavior?.

The cell will reveal left and right buttons within the same gesture action. I mean you can start panning to the right to reveal left buttons then continue panning to the left to reveal right buttons without having to release your touch. Other similar controls do not behave like that, but in this case it was designed that way on purpose. If this is not desirable it should be easy to add a property to prevent this, so to prevent left revealing when you started showing right buttons and vice-versa. Would that make sense?

Thanks

**Comment by stevemckenzie** [comment]
I don't think that's the issue. It looks like an animation glitch from something. My guess just something odd with the changes Apple has made to cells in iOS 8. 

I had a deadline this week so I wasn't able to better dive into this stuff including the other issue I posted about.

Hopefully I can get you that sample app soon and maybe see if I can better understand this issue as well.

Happy to help make this more stable as I just submitted an app to the AppStore using it.

Thanks for making it as well :)

**Comment by stevemckenzie** [comment]
OK, after testing more, this only appears to happen for me when compiled with Xcode 5, but testing on an iOS 8 device.

To describe what I see more, basically if you drag to reach the threshold as to where you have panned enough to allow all the buttons to be revealed, you will see the cell quickly return to SWCellRevealPositionCenter but then animate to reveal all buttons. If you do not reach the threshold, the animation will work as expected and animate back to SWCellRevealPositionCenter.

So I wouldn't worry about this for now. Not a fan of seeing it but iOS 8 is still beta and as well, building with Xcode 6 does not have the issue.
