### ISSUE TITLE
Can't delete cells in the default edit mode

### ISSUE THREAD

**Issue by rubyboy** [John-Lluch/SWRevealTableViewCell#12]
Using the Example app, add the following line at the end of viewDidLoad in TableViewController:
    self.tableView.editing = YES;
This will start the app in an editable mode, showing the default delete button on the left edge of the cells. Now, when clicking any of the delete buttons it shows the delete confirmation button briefly on the right but then hides it.

**Comment by John-Lluch** [comment]
Please add this just below the call to `[super layoutSubviews]` in `-(void)layoutSubviews`

```
    // do not mess with Apple implementation if we do not want our custom layout to be supported on edit mode.
    if ( !_allowsRevealInEditMode && self.editing )
        return;
```

This will preserve Apple's implementation on edit mode if you leave `allowsRevealInEditMode` property to NO. Still, I am not totally sure of what is the best approach for this. To some extend the class supersedes Apple's implementation and replaces it to an alternative (thought equivalent) behavior. Ultimately you must chose one of the two approaches and avoid trying to mix both of them. I mean, if you want to present a 'delete' button using this class then you should configure your cells to prevent Apple's delete button to appear. Does this make sense?

**Comment by John-Lluch** [comment]
Sorry, didn't meant to close that one. Reopening it. :-)

**Comment by rubyboy** [comment]
I think what you said makes sense.
Awesome fix. Worked well.
Thanks for the super speedy response!
