### ISSUE TITLE
Fire rightbuttons on tap cell

### ISSUE THREAD

**Issue by jimmyaat10** [John-Lluch/SWRevealTableViewCell#14]
Hi,
I need to fire the right buttons when the user tap a Cell. How can I do it?
- (void)tableView:(UITableView _)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath{
  //[tableView deselectRowAtIndexPath:indexPath animated:YES];
  SWRevealTableViewCell *cell = (SWRevealTableViewCell_)[tableView cellForRowAtIndexPath:indexPath];
  [self rightButtonItemsInRevealTableViewCell:cell];
  }
  Thanks!

**Comment by John-Lluch** [comment]
The method to programmatically reveal your cell button items is setRevealPosition:animated.

Thanks
