### ISSUE TITLE
Crash - Happens if the reveal menu is opened and a full screen transition happens

### ISSUE THREAD

**Issue by FramusRock** [John-Lluch/SWRevealTableViewCell#16]
Hey!

First of all thanks for the good work, I really appreciate the SWRevealTableViewCell!

I've got the reveal menu opened in one of my TableViewCells, if I do a full screen transition to another screen (that also has a TableView with reveal function), it crashes.

If I change the reveal position of all SWRevealTableViewCells to center in viewWillDisappear, the crash won't happen.  This comes in combination with weird flashes on my TableViewCells.

I hope you have an idea how to fix this!

Cheers,
Max

**Comment by John-Lluch** [comment]
Your description is rather unespecific. Please can you post the reason of the crash or better yet a simple example demonstrating this? That's really the only way for me to understand what is going on, as it does not happen on any of my uses of the class. Thanks.

**Comment by FramusRock** [comment]
Thanks for the fast repsonse. Sorry, you are right. Here's a screenshot of the stack trace and line of crash.

Xcode shows this as crash reason:
**\* Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan 29.75]'

![1](https://cloud.githubusercontent.com/assets/1455240/3977982/91b3ebca-2841-11e4-8c11-5c5e69074d60.png)
![2](https://cloud.githubusercontent.com/assets/1455240/3977981/91b3c3ac-2841-11e4-8e58-9b7ab9a21070.png)

**Comment by John-Lluch** [comment]
Ok, but please does this still happen if you explicitly set a width on your cellButtonItems?

**Comment by FramusRock** [comment]
Yes, I'm already setting an explicit width (I used your example as a starting point).

**Comment by John-Lluch** [comment]
So why it does not happen on the example. What's the difference?

**Comment by FramusRock** [comment]
It happens the second I do a full screen transition (with pushViewController) on my NavigationController (not the one holding the table view with the reveal cells) and if one of the cells in the TableView is still revealed.

There are no transitions in the example, so you can't make the example crash with this.

**Comment by John-Lluch** [comment]
Can you prepare a simple example demonstrating this. I am willing to solve this issue as I think it is the second time it is reported, but I can't reproduce it. Thanks

**Comment by FramusRock** [comment]
I'm just trying to reproduce it in your example, it also can't make it happen here at the moment. I thought it was easier to reproduce.....
If this helps, the X and width value of the frame at the crash-line are both NaN.
I'll post again as soon as I get an example to work.

**Comment by FramusRock** [comment]
I found out that it happens if a revealed TableViewCell gets reused by another TableView  when using reusable cells.  Does this help you? I can't find out more.

**Comment by John-Lluch** [comment]
You mean, a _different_ instance of a UITableView reusing the same instance of a UITableViewCell? Is that even possible?. So how do you get to that?
Thanks

**Comment by FramusRock** [comment]
No sorry, as far as I know that's not possible.

I found out what was causing it. I have a custom UITableViewController subclass and the viewWillAppear of this does get called in a weird order when a full screen transition happens:

So if I do a full screen transition whereas both screens have the custom UITableViewController, this happens:

-viewWillDisappear (oldTableViewController)
-viewWillAppear      (oldTableViewController)
-viewWillAppear      (newTableViewController)
-viewWillDisappear (oldTableViewController)

so basically, when only one time viewWillDisappear should get called, it calls disappear, appear, disappear. This caused the problems and I still have no idea how and why this can happen. I checked for all kinds of addSubview calls etc, but nothing like this is happening here.
When transitioning away from the current top level view, it tells a subview, my UITableViewController subclass, that it just appear and then disappears...

So sorry, it was my mistake. If you have a spontaneous idea where the weird calls for viewWillAppear could come from, please tell me ;)

![bildschirmfoto 2014-08-20 um 15 13 55](https://cloud.githubusercontent.com/assets/1455240/3981246/fd47f302-286b-11e4-9422-dbf2cf800edf.png)

**Comment by John-Lluch** [comment]
Hi, it seems the order appearance methods are called is messed up each time Apple releases an OS, but still the class should not crash. I will think on what could cause the crash given that. Thanks for all your feedback.

**Comment by FramusRock** [comment]
Yes, I've also seen that, I took care now that all kinds of wrong orders don't cause my app to crash.
I just had the crash happen doing a transition to another UITableViewController (I have kind of a tree structure in my TableView). It happened on calling "cellForRowAtIndexPath", maybe this helps finding it. I'll just reset the cells manually in viewWillDisappear for now. It's not a shiny solution, but at least there's a workaround. 
Thanks for your help.

**Comment by John-Lluch** [comment]
Please, can you test what I just pushed (version v0.3.5) on your app?

I replaced 'didMoveToWindow' by 'didMoveToSuperview'. I thought that both were equivalent for the purposes of this class but it turned to be that on iOS8 the former is called at times I didn't expect.

Thanks

**Comment by FramusRock** [comment]
Thank you, it seems like this fixed it! Though I'm still on iOS 7. Is it possible that the same applied also to iOS 7?

**Comment by John-Lluch** [comment]
Ah, right. Yes maybe this was an issue on both iOSes. I made the change on XCode 6 and iOS8 simulator because I thought this is where the problem surfaced.

**Comment by FramusRock** [comment]
Ah, I see. Thanks a lot for helping me, it was definitely nice to meet you!
By the way I knew you before from the SWRevealViewController, so I was very happy to explore something else with the SW prefix.  ;)

**Comment by John-Lluch** [comment]
My pleasure. Thanks to you for using this control.
