### ISSUE TITLE
Default methods of `dataSource`

### ISSUE THREAD

**Issue by jonghwanhyeon** [John-Lluch/SWRevealTableViewCell#3]
Hello,
I think that it will be good to support default methods of `dataSource`. For example, `leftButtonItemsInRevealTableViewCell:` will return `@[]` if `dataSource` does not respond to `leftButtonItemsInRevealTableViewCell:`

**Comment by John-Lluch** [comment]
You are right, I will make them @optional. Thanks for your suggestion.

**Comment by John-Lluch** [comment]
This is done.
