### ISSUE TITLE
single cell opened

### ISSUE THREAD

**Issue by mythodeia** [John-Lluch/SWRevealTableViewCell#4]
Hello @John-Lluch  and thanks for open sourcing this lib of yours.
I have a question regarding the numbers of cells that are left opened after swipe.
Is it possible to make it work by having only 1 item opened at each time.

Take a look at your Phone app. if you swipe to delete a call and then try to swipe at another cell or even touch your previous cell gets swiped back to its default location.

thanks

**Comment by John-Lluch** [comment]
The  example in the repo already does that. Isn't this what you mean?
Thanks

**Comment by mythodeia** [comment]
@John-Lluch i mean when swiping another cell not only tapping it.
thanks

**Comment by John-Lluch** [comment]
Have you tried the example? It does nothing by tapping. It unreveals buttons on the revealing cell when you reveal a new one. What am I missing?  Thanks

**Comment by mythodeia** [comment]
@John-Lluch 
my mistake. i had a another version where on the didSelectRowAtIndexPath there was this code:
    SWRevealTableViewCell *cell = (id)[tableView cellForRowAtIndexPath:indexPath];
    [cell setRevealPosition:SWCellRevealPositionLeft animated:YES];
and i had it uncommented

thanks
