### ISSUE TITLE
use custom UITableViewCell with SWRevealTableViewCell

### ISSUE THREAD

**Issue by gautierdelorme** [John-Lluch/SWRevealTableViewCell#9]
Hi !
I'm trying to use your wonderful SWRevealTableViewCell with my custom UITableViewCell but I can't... I have juste blank cell.
Can you help me ? I have my custom cell in a .xib and my class (FeedTableCell) contains only a image view, a label and a text view.

Thanks for your help !

Gautier

**Comment by John-Lluch** [comment]
You just have to make your cell a subclass of SWRevealTableViewCell. There's really nothing more on this.

**Comment by gautierdelorme** [comment]
Yes but it doesn't work, probably because of me but I can't see my mistake. Can you help me please ?

In my **FeedTableCell.h** : 

``` objective-c
#import "SWRevealTableViewCell.h"
@interface FeedTableCell : SWRevealTableViewCell
@property (nonatomic, weak) IBOutlet UILabel *title;
@property (nonatomic, weak) IBOutlet UITextView *content;
@property (nonatomic, weak) IBOutlet UIImageView *image;
@end
```

and in my controller : 

``` objective-c
static NSString *CellIdentifier = @"FeedTableCell";
- (void)viewDidLoad
{
   ....
   [_tableView registerClass:[FeedTableCell class] forCellReuseIdentifier:CellIdentifier];
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {

    FeedTableCell *cell = [tableView dequeueReusableCellWithIdentifier:CellIdentifier forIndexPath:indexPath];

    cell.dataSource = self;
    cell.selectionStyle = UITableViewCellSelectionStyleNone;
    cell.title.text = @"My title";
    cell.content.text = @"My content";
    cell.image.image = [UIImage imageNamed:@"HoneyTot.png"];
    cell.cellRevealMode = SWCellRevealModeReversedWithAction;

    return cell; 
}
```

Do you see a error ? :/

Thanks for your help ! :)

**Comment by maddoggy1979** [comment]
In your controller, do you have this up the top of either your .h or .m? If not, your controller doesn't know its supposed to act on SWRevealTableViewCell methods etc.

``` Objective-C
@interface YourTableViewController () <SWRevealTableViewCellDelegate,SWRevealTableViewCellDataSource>

```

**Comment by John-Lluch** [comment]
@gautierdelorme , on your post you say that you just have a blank cell, but you do not mention anything about the SWRevealTableViewCell particular features. What is the actual difference between subclassing your cell directly from UITableViewCell and from SWRevealTableViewCell?, the latter is just a subclass of the former that adds a view for utility buttons, so there should be no difference on what is presented on your content view... no?, please can you be more specific about what is the actual issue with this class? Thanks.

**Comment by gautierdelorme** [comment]
@maddoggy1979 Yes of course i have this : 

``` objective-c
#import "SWRevealTableViewCell.h"
#import "FeedTableCell.h"
@interface OnEnterConnectedViewController : UIViewController <SWRevealTableViewCellDelegate,SWRevealTableViewCellDataSource, UITableViewDelegate, UITableViewDataSource>
```

My cell is a subclass of SWRevealTableViewCell, and when I swipe, I can see utility buttons of SWRevealTableViewCell so it's work but my content doesn't appear. My cell should be like this : 

![capture decran 2014-07-27 a 09 03 14](https://cloud.githubusercontent.com/assets/6973663/3713245/dd7db7b8-155c-11e4-93ca-79fba2d52bd0.png)

But I have just a blank cell when I run...

When I add this : 

``` objective-c
cell.textLabel.text =@"Test textLabel";
```

I can see the text but not the title, image and content of my custom class...

I want to subclassing my cell directly from SWRevealTableViewCell to have your awesome features that I love ! :)

**Comment by gautierdelorme** [comment]
Ok guys I fixed it.. Just add in your viewDidLoad method : 

``` objective-c
[_tableView registerNib:[UINib nibWithNibName:CellIdentifier bundle:[NSBundle mainBundle]] forCellReuseIdentifier:CellIdentifier];
```

Thanks a lot for your help ! :)
